# Generated by Django 5.0.3 on 2024-08-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
